use casestudy1;

Select * from Fact;
Select * from Location;
Select * from product;

-- Q1. Display the number of states present in the LocationTable.

Select count(distinct state) from Location;

-- Q2. How many products are of regular type?

Select count(*) from 
Product where Type = 'Regular';

-- Q3. How much spending has been done on marketing of product ID 1?

Select sum(marketing) from 
Fact where ProductId = 1;

-- Q4. What is the minimum sales of a product?

Select min(sales) from Fact;

-- Q5 Display the max Cost of Good Sold (COGS).

Select max(COGS) from fact;

-- Q6. Display the details of the product where product type is coffee

Select * from Product where Product_Type = 'Coffee';

-- Q7. Display the details where total expenses are greater than 40

SELECT * from Fact
where Total_Expenses > 40;

-- Q8. What is the average sales in area code 719?

Select avg(Sales) from Fact
where Area_Code = 719;

-- Q9. Find out the total profit generated by Colorado state.

Select sum(profit) from Fact 
where Area_Code in 
(Select Area_Code from Location where state = 'Colorado');

-- Q10 .Display the average inventory for each product ID.

Select avg(inventory) as Average_ProductId from Fact
group by ProductId;

-- Q11. Display state in a sequential order in a Location Table.

Select distinct state from LOCATION
order by state asc;

-- Q12. Display the average budget of the Product where the average budget
-- margin should be greater than 100.

Select productId, avg(budget_margin) as budget_margin
from fact 
group by productId 
having avg(budget_margin) > 100;

-- Q13 What is the total sales done on date 2010-01-01

Select sum(sales) from Fact 
where Date = '2010-01-01';

-- Q14. Display the average total expense of each product ID on an individual date.

Select avg(Total_Expenses) as Total_Expenses, Date, ProductId
from Fact 
group by ProductId, Date
order by ProductId, Date;

-- Q15. Display the table with the following attributes such as date, product ID, product_type, product, sales, profit, state, areacode.

Select Date, f.ProductId, p.Product_Type, Sales, Profit, state, f.Area_Code
from Product p right join Fact f on p.productId = f.productId 
left join Location l on f.Area_Code = l.Area_Code;

-- Q16. Display the rank without any gap to show the sales wise rank.

Select Sales, dense_rank() OVER (order by Sales desc) as Sales_Rank
from fact;

-- Q17. Find the state wise profit and sales.

Select sum(Sales) as Total_Sales, l.state 
from Fact f LEFT join LOCATION l 
on f.Area_Code = l.Area_Code
group by l.state
order by l.state asc;

-- Q18. Find the state wise profit and sales along with the product name.

Select Product, sum(Sales) as Total_Sales, sum(profit) as Total_Profit, l.state 
from Location l right join Fact f 
on l.Area_Code = f.Area_Code
join Product p on f.ProductId = p.productId
group by f.productId, l.state, Product
order by Product, l.state asc;

-- Q19. If there is an increase in sales of 5%, calculate the increasedsales.

SELECT sales, (sales) * 0.05 AS increased_total_sales, (sales) * 1.05 AS new_sales
FROM fact;

-- Q20. Find the maximum profit along with the product ID and producttype.

Select top 1 sum(profit) as max_profit, f.productId, p.Product_Type
from fact f join Product p on f.productId = p.productId
group by f.productId, product_type
order by max_profit desc;

-- Q21. Create a stored procedure to fetch the result according to the product type
-- from Product Table.

Create PROCEDURE getbyproduct_type @product_Type VARCHAR(50)
as begin 
    Select * from product
    where Product_Type = @product_Type
END;
GO

EXEC getbyproduct_type  @product_Type = 'Coffee';

-- Q22. Write a query by creating a condition in which if the total expenses is less than
--60 then it is a profit or else loss

Select Total_Expenses, (
    Case when Total_Expenses <= 60 then 'Profit'
    else 'Loss'
    END
) as Profit_or_loss
from Fact;

-- Q23 Give the total weekly sales value with the date and product ID details. Use
-- roll-up to pull the data in hierarchical order.

DECLARE @FirstDate DATE;
SELECT @FirstDate = MIN(Date) FROM fact;
SELECT 
    ProductID,
    DATEADD(DAY, 7 * ((DATEDIFF(DAY, @FirstDate, Date)) / 7), @FirstDate) AS WeekStart,
    DATEADD(DAY, 6, DATEADD(DAY, 7 * ((DATEDIFF(DAY, @FirstDate, Date)) / 7), @FirstDate)) AS WeekEnd,
    SUM(Sales) AS Total_Sales
FROM fact
GROUP BY ROLLUP(
    ProductID, 
    DATEADD(DAY, 7 * ((DATEDIFF(DAY, @FirstDate, Date)) / 7), @FirstDate)
)
ORDER BY WeekStart, ProductId;

-- Q24. Apply union and intersection operator on the tables which consist of
-- attribute area code.

-- Union 
SELECT area_code FROM fact
UNION
SELECT area_code FROM Location;

-- Intersect
SELECT area_code FROM fact
intersect
SELECT area_code FROM Location;

-- Q25. Create a user-defined function for the product table to fetch a particular
-- product type based upon the user’s preference.

CREATE or Alter FUNCTION fetch_product(@Product_Type VARCHAR(50))
RETURNS TABLE
AS
RETURN
(
    SELECT Product, type, product_type
    FROM Product
    WHERE product_type = @Product_Type
);
GO

Select * from fetch_product('Coffee');

-- Q26. Change the product type from coffee to tea where product ID is 1 and undo it.

-- Start a transaction
BEGIN TRANSACTION;

-- Step 1: Update product_type to 'Tea' for ProductID = 1
UPDATE Product
SET product_type = 'Tea'
WHERE ProductID = 1;

-- Checking the table changes
SELECT ProductID, Product, product_type
FROM Product
WHERE ProductID = 1;

-- Step 2: Undo the change
ROLLBACK TRANSACTION;

-- Checking the product table again
SELECT ProductID, Product, product_type
FROM Product
WHERE ProductID = 1;

-- Q27. Display the date, product ID and sales where total expenses are
-- between 100 to 200.

Select * from fact;

Select date, ProductId, Sales, Total_Expenses
from fact
WHERE Total_Expenses >= 100 and Total_Expenses < = 200

-- Q28. Delete the records in the Product Table for regular type.

-- Start a transaction
BEGIN TRANSACTION;

SELECT *
FROM Product
WHERE type = 'Regular';

DELETE FROM Product
WHERE type = 'Regular';

SELECT *
FROM Product;

-- Undo the deletion if needed
ROLLBACK TRANSACTION;  -- restores all deleted rows

-- Q29. Display the ASCII value of the fifth character from the columnProduct.

Select distinct Product_Type,
ASCII(SUBSTRING(Product_Type, 5, 1)) as ASCII_FIFTH
from Product

